name: template FunctionApp1 cd

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: windows-latest
      env:
        description: Environment deploy to
        type: string
        default: DEV
      kvname:
        description: keyvault name
        type: string
        default: kvabdev

jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.env }}

    steps:
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "${{ inputs.kvname }}"
        secrets: 'Function1FuncAppName, Function1IntPublishProfile'
      id: kvSecret
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: FunctionZip
        path: ./artifacts
    - name: Run a one-line script
      run: ls -l ./artifacts
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.6
      with:
        app-name: ${{ steps.kvSecret.outputs.Function1FuncAppName }}
        package: ./artifacts/FunctionApp.zip
        publish-profile: ${{ steps.kvSecret.outputs.Function1IntPublishProfile }}